### ISSUE TITLE
Importing openstack_compute_instance_v2 resource doesn't pull in existing network port id.

### ISSUE THREAD

**Issue by easpeagle** [terraform-provider-openstack/terraform-provider-openstack#1561] opened 2023-05-02 18:47 UTC
### Terraform Version
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.51.1

### Affected Resource(s)
openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
## instance
module "<instance>" {
  source  = "path/to/module"
  version = "x.y.z"

  port_name        = "<instance>_int_port"
  port_description = "network port on <network>"
  network_id       = <data resource network id>
  security_group_ids = [
    <some security group ids>
  ]

  assign_fip    = true
  fip_pool_name = <fip network name>

  instance_name        = "<instance>"
  instance_flavor_name = "<flavor>"
  instance_key_pair    = <key pair name>
  instance_user_data   = null

  volume_storage = [
    {
      name                 = "<instance>-vda"
      description          = "<instance> boot volume"
      size                 = 30
      enable_online_resize = true
      uuid                 = "<volume id>"
      source_type          = "volume"
      boot_index           = 0
      }, {
      name                 = "<instance>-vdb"
      description          = "<instance> data volume"
      size                 = 50
      enable_online_resize = true
      uuid                 = "<volume id>"
      source_type          = "volume"
      boot_index           = null
    }
  ]
}

## module
resource "openstack_networking_port_v2" "instance_net_port" {
  name               = var.port_name
  description        = var.port_description
  network_id         = var.network_id
  admin_state_up     = "true"
  security_group_ids = var.security_group_ids
}

resource "openstack_networking_floatingip_v2" "instance_fip" {
  count = var.assign_fip == true ? 1 : 0
  pool  = var.fip_pool_name
}

resource "openstack_networking_floatingip_associate_v2" "instance_fip_assoc" {
  count       = var.assign_fip == true ? 1 : 0
  floating_ip = openstack_networking_floatingip_v2.instance_fip[0].address
  port_id     = openstack_networking_port_v2.instance_net_port.id
}

resource "openstack_blockstorage_volume_v3" "block_device" {
  timeouts {
    create = "60m"
    delete = "60m"
  }

  for_each = {
    for each in var.volume_storage : each.name => each
  }

  name                 = each.value.name
  description          = each.value.description
  size                 = each.value.size
  enable_online_resize = each.value.enable_online_resize
  image_id             = each.value.source_type == "image" ? each.value.uuid : null
}

resource "openstack_compute_instance_v2" "instance_compute" {
  name        = var.instance_name
  flavor_name = var.instance_flavor_name
  key_pair    = var.instance_key_pair
  user_data   = var.instance_user_data

  dynamic "block_device" {
    for_each = openstack_blockstorage_volume_v3.block_device

    content {
      uuid                  = openstack_blockstorage_volume_v3.block_device[block_device.value.name].id
      source_type           = "volume"
      destination_type      = "volume"
      boot_index            = var.volume_storage[index(var.volume_storage.*.name, block_device.value.name)].boot_index
      volume_size           = block_device.value.size
      delete_on_termination = var.volume_storage[index(var.volume_storage.*.name, block_device.value.name)].delete_on_termination
    }
  }

  network {
    port = openstack_networking_port_v2.instance_net_port.id
  }
}

```

### Expected Behavior
The resources for this instance were imported thusly:
```bash
terraform import module.<instance>.openstack_networking_port_v2.instance_net_port <port id>
terraform import module.<instance>.openstack_networking_floatingip_associate_v2.instance_fip_assoc[0] <fip id>
terraform import module.<instance>.openstack_networking_floatingip_v2.instance_fip[0] <fip id>
terraform import module.<instance>.openstack_compute_instance_v2.instance_compute <instance id>
```
When imported, I expect the compute instance resource to have pulled in the uuid for the network port

### Actual Behavior
When imported, the network block in the terraform state includes only the network uuid and not the network port uuid.

```bash
    network {
        access_network = false
        fixed_ip_v4    = "<correct IP>"
        mac            = "<correct MAC>"
        name           = "<correct network name>"
        uuid           = "<correct network id>"
    }
```

Note the missing `port = <some port id>` ... and that results in an apply that causes a replacement.

```bash
      ~ network {
          ~ fixed_ip_v4    = "<correct IP>" -> (known after apply)
          + fixed_ip_v6    = (known after apply)
          + floating_ip    = (known after apply)
          ~ mac            = "<correct MAC>" -> (known after apply)
          ~ name           = "<correct network name>" -> (known after apply)
          + port           = "<correct port id>" # forces replacement
          ~ uuid           = "<correct network id>" -> (known after apply)
            # (1 unchanged attribute hidden)
        }
```

**Comment by nikParasyr** [comment] 2023-05-04 13:57
Duplicate of #1280 which provides more info.
Closing

**Closed by nikParasyr** 2023-05-04 13:57 UTC
