### ISSUE TITLE
Replacing openstack_compute_keypair_v2 public_key value results in ID change

### ISSUE THREAD

**Issue by dms-cat** [terraform-provider-openstack/terraform-provider-openstack#980] opened 2020-03-11 21:26 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.12.23
+ provider.openstack v1.26.0
+ provider.powerdns v1.3.0
```

### Affected Resource(s)

- `openstack_compute_keypair_v2`

### Terraform Configuration Files
```hcl
resource openstack_compute_keypair_v2 developers {
  name = "developers"

  public_key = join(
    "",
    list(
      file("public_keys/jane_doe"),
      file("public_keys/john_doe")
    )
  )
}
```

### Debug Output

[Gist](https://gist.github.com/dms-cat/f739ec1ce6abd3846b1a9f4dd7096ce4)

### Expected Behavior

The ID should stay the same.

### Actual Behavior

The ID, even though it is clearly the same as the name, is marked as "(known after apply)."<del>, which means every resource — for example `openstack_compute_instance_v2` — which depends on it has to be recreated. Is there a fundamental limitation of OpenStack that a change to a public key necessitates recreating every dependent resource?</del> <ins>Looks like that was instead an artefact of not having the latest state locally</ins>.

### Steps to Reproduce

1. Set a public key.
1. `terraform apply`
1. Modify the public key.
1. `terraform apply`

**Comment by ozerovandrei** [comment] 2020-03-13 07:04
Hi @dms-cat.

Resource is recreated because there is no way to update a keypair in the API: https://docs.openstack.org/api-ref/compute/#keypairs-keypairs.

**Comment by l0b0** [comment] 2020-03-15 05:24
@ozerovandrei Actually, even though keypairs have to be recreated the associated resources are *not* recreated (that part was a red herring). So the problem is *much* smaller than originally thought, because the only problem is that terraform reports an ID change, which would *normally* result in replacing all related resources.

**Comment by ozerovandrei** [comment] 2020-03-17 06:03
I guess it's because we use `name` argument as ID to `compute_keypair_v2` resource: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_keypair_v2.go#L84

We do it because OpenStack Compute V2 API doesn't have ID to keypair object in API: 
But I see that keypair should have have an ID in the GET response: 
https://docs.openstack.org/api-ref/compute/?expanded=show-keypair-details-detail

It should be tested and added into Gophercloud: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/keypairs/results.go#L10
We can then update the provider to use the valid ID instead of name to fix this issue.

**Comment by kayrus** [comment] 2020-04-24 08:26
@ozerovandrei keypair doesn't return an ID even in the latest API microversions. According to nova code, it should be returned: https://github.com/openstack/nova/blob/2cddf595a8cdedbdb844e800d853ea143817b545/nova/objects/keypair.py#L98, but a special func filters fields out: https://github.com/openstack/nova/blob/stable/train/nova/api/openstack/compute/keypairs.py#L44

This code was removed in ussuri: https://github.com/openstack/nova/commit/f3ae221f60c5dc51f5c3936cb3c3c1439157dedb#diff-965dd41990282863f6bf72aa9d885057
I believe we cannot use use IDs as a general available feature.

**Comment by ozerovandrei** [comment] 2020-09-12 07:47
Closing because we can only use keypair name and ID is unavailable unfortunately.

**Closed** 2020-09-12 07:48 UTC
Labels: enhancement, question, upstream
