### ISSUE TITLE
PreconditionFailed in swift backend 

### ISSUE THREAD

**Issue by smrcascao** [terraform-provider-openstack/terraform-provider-openstack#733] opened 2019-04-16 13:26 UTC
Hi there,

I'm setting up swift as backend for terraform tfstate. However, I'm always getting a "PrecontionFailed" error message.

### Terraform Version
Terraform v0.11.13
+ provider.openstack v1.16.0

### Affected Resource(s)
tfstate

### Terraform Configuration Files
```hcl
terraform {
  required_version = "=v0.11.13"
  backend "swift" {
    container         = "terraform_state"
    archive_container = "terraform_state_archive"
  }
}
provider "openstack" {
  version = "1.16"
}
```

### Expected Behavior
tfstate should be persisted in a object-store container

### Actual Behavior
tfstate is never persisted and I'm getting a PreconditionFailed error message

**Comment by kayrus** [comment] 2019-04-16 13:47
Try to adjust the HCL configuration as stated below:

```hcl
terraform {
  required_version = "0.11.13"
  backend "swift" {
    container         = "terraform_state"
    archive_container = "terraform_state_archive"
  }
}
provider "openstack" {
  version = "1.16.0"
}
```

If it doesn't help, make sure that swift containers exist. If they don't, try to create them, e.g.:

```sh
$ swift post terraform_state
$ swift post terraform_state_archive
```

**Comment by noeliajimenezg** [comment] 2019-06-06 11:02
I having the same issue using Terraform 0.12 and OpenStack provider 1.19. I run the following tests:
- Starting from a point with no containers in OpenStack and not giving the field "archive_container", Terraform creates correctly the container in the field "container".
- Starting from a point with no containers in OpenStack and giving the field "archive_container", Terraform creates correctly the container in the field "archive_container" but it gives an error 412 PreconditionFailed for the "container".
- Starting from a point where the "container" was already created with Terraform in OpenStack and running a second time with the "archive_container" informed, Terraform shows an error 412 PreconditionFailed for the update of the "container".

**Comment by kayrus** [comment] 2019-06-06 11:22
openstack provider is not responsible to the backend state logic. Try to ask in https://github.com/hashicorp/terraform/pull/20211

**Comment by rguichard** [comment] 2019-07-30 11:36
Hi there,

I have also the same issue with the Swift Backend (exact same behavior as @noeliajimenezg), with Terraform 0.11.7 et OpenStack provider 1.19.

However I have also the issue with `openstack_objectstorage_container_v1`. I use the exact same piece of code as the documentation (https://www.terraform.io/docs/providers/openstack/r/objectstorage_container_v1.html).

If I enable the versioning, I end up with the 412 PreconditionFailed error. The same I have with the Swift Backend.

```
1 error(s) occurred:

* module.compute.openstack_objectstorage_container_v1.container_1: 1 error(s) occurred:

* openstack_objectstorage_container_v1.container_1: Error creating OpenStack container: Expected HTTP response code [201 202 204] when accessing [PUT http://10.197.214.10:8080/swift/v1/tf-test-container-1], but got 412 instead
{"Code":"PreconditionFailed","BucketName":"tf-test-container-1","RequestId":"tx0000000000000000774c0-005d402805-eb79r6-default","HostId":"eb796-default-default"}
```

If I don't enable the versioning, it works nicely.

As stated above, if I enable the versioning later, I still end up with the 412.

**Comment by rv0147** [comment] 2019-09-16 05:20
I have same issue as well. I am able to create container terraform_state successfully when used with swift backend.  However, it doesn't create the terraform.tf state file in the container. My container shows  0 bytes and object count is 0

I am on openstack provider v1.22 and terraform v0.12.6

provider "openstack" {
  version = "1.22"
}

terraform {
  required_version = "=v0.12.6"
  backend "swift" {
    auth_url = var.authurl
    user_domain_name = var.domainname
    region_name = var.regionname
    tenant_id = var.tenantid
    user_name = var.username
    password = var.passwd
    container = "terraform_state"

  }
}

**Comment by rv0147** [comment] 2019-09-16 05:42
I did remove archive_container in my configuration as i am receiving pre condition failed in swift backend error after execution

**Comment by springfan** [comment] 2020-04-03 15:44
> I did remove archive_container in my configuration as i am receiving pre condition failed in swift backend error after execution

Was facing 412 as well. Removnig  archive_container fixed the issue.

**Comment by dejwsz** [comment] 2020-07-27 13:47
Is it working for anyone? I have "PreconditionFailed" error too.

**Comment by dejwsz** [comment] 2020-07-27 13:56
If I remove "archive_container" then it works. So the issue is related to archive container only.

**Comment by dejwsz** [comment] 2020-07-28 20:50
So is the versioning working for Swift backend or not? any clue? anyone used it with a success?

**Comment by springfan** [comment] 2020-07-29 05:42
> So is the versioning working for Swift backend or not? any clue? anyone used it with a success?

Yes it work's.

`terraform {
  backend "swift" {
    container         = "my-container-terraform-state"
    user_domain_name = "yyy"
    auth_url         = "http://xxxxxxxxxx:5000/v3/"
    region_name      = "region-xxxx"
    tenant_id        = "xxxxxxx"
  }
}
`

**Comment by dejwsz** [comment] 2020-07-29 09:47
Hmm, but in your example there is no "archive_container". It works for me
with "container" only; "archive_container" turns versioning on. Is it
working for you?

śr., 29 lip 2020 o 07:42 springfan <notifications@github.com> napisał(a):

**Comment by kayrus** [comment] 2023-06-29 21:31
Thanks to hashicorp for not being interested in swift backend maintainers. Closing this.

**Closed by kayrus** 2023-06-29 21:31 UTC
