### ISSUE TITLE
Can't set blockstorage quota per volume type

### ISSUE THREAD

**Issue by fitbeard** [terraform-provider-openstack/terraform-provider-openstack#1193] opened 2021-03-10 07:43 UTC
### Terraform Versions
Terraform: v0.14.7
OpenStack provider: v1.39.0

### Affected Resource(s)
blockstorage_quotaset_v2
blockstorage_quotaset_v3

### Terraform Configuration Files
```hcl
resource "openstack_blockstorage_quotaset_v3" "quotaset_1" {
  project_id = "88b769ef67994cd2910f143c87283904"
  region = "region-1"
  volumes   = 10
  snapshots = 10
  gigabytes = 20
  per_volume_gigabytes = -1
  backups = 0
  backup_gigabytes = 0
  groups = 10
  volume_type_quota = {
    volumes_standard = 10
    gigabytes_standard = 20
    snapshots_standard = 10
  }
}
```

### Debug Output
https://gist.github.com/fitbeard/0aa89097ecfe42d6f00648499ed4616c

### Expected Behavior
Volume type quotas created/updated

### Actual Behavior
Getting `"badRequest": {"code": 400, "message": "The server could not comply with the request since it is either malformed or otherwise incorrect."`

### Steps to Reproduce
Describe volume type quotas
1. `terraform apply`

### Important Factoids
OpenStack release: Ussuri
Cinder version: 16.2.1
Cinder V2 API: 2.x?
Cinder v3 API: 3.60

**Comment by fitbeard** [comment] 2021-03-10 07:44
@nikParasyr

**Comment by nikParasyr** [comment] 2021-03-10 07:48
@fitbeard can i get a gist with debug level logs?

**Comment by nikParasyr** [comment] 2021-03-10 07:54
> @fitbeard can i get a gist with debug level logs?

TF_LOG=DEBUG terraform apply

Also can you ensure that the project in question has access to the "standard" volume type? Although in that case i think the error message is different

**Comment by fitbeard** [comment] 2021-03-10 08:03
@nikParasyr by the way. This happens with application credentials and old style creds .

**Comment by nikParasyr** [comment] 2021-03-10 08:25
@fitbeard thanks for the info.

Unfortunately when adding this feature I couldn't add tests as we lack a volume_type resource --which i aim to add soon. That being said i tested it locally back then and also now, with your exact snippet and it works fine. terraform version and provider same as yours, on openstack stein clusters though although that shouldn't be an issue *in theory*....

> This happens with application credentials and old style creds .

This shouldn't be affecting it. By old style creds i guess you mean typical openrc file sourced? 

The logs unfortunately are not super helpful. Could you check a thing for me if possible:
- what happens if you remove the 'volume_type_quota` block


I'll look a bit more into it later today or tomorrow

**Comment by fitbeard** [comment] 2021-03-10 08:39
@nikParasyr 
Debug output without `volume_type_quota` block: https://gist.github.com/fitbeard/992045f05e17f93dd16f2c09b8ed934a

When I saw debug output I remembered one breaking change in Cinder happened with Ussuri release: https://docs.openstack.org/releasenotes/cinder/ussuri.html#relnotes-16-2-0-stable-ussuri-upgrade-notes
`__DEFAULT__ ` volume type was introduced. This type is let's say `indelible`. Starting Ussuri without it Cinder bootstrap is impossible. Max what can you do is to disable it.

> By old style creds i guess you mean typical openrc file sourced?

Yes.

**Comment by nikParasyr** [comment] 2021-03-10 15:23
@fitbeard Thanks for all the help.

I'm able to replicate on an ussuri devstack. I also have a good idea of what the issue is. I'll start working on it later this week. I'd prefer to add the volume type resource as well and update the tests to cover it as well. That might take a bit longer but i prefer it this way to avoid similar issues.

**Comment by nikParasyr** [comment] 2021-03-24 06:55
@fitbeard fix was released in 1.40.

**Comment by nikParasyr** [comment] 2021-03-24 09:12
@fitbeard can you check if it works for you and if so close the issue? i did run the tests on a latest devstack and they passed

**Comment by fitbeard** [comment] 2021-03-28 13:24
@nikParasyr on Ussuri/Victoria everything looks good now. Tried with few types. Already using in production. Big thanks!

**Closed** 2021-03-31 12:38 UTC
