### ISSUE TITLE
[OpenTofu] Signature validation was skipped due to the registry not containing GPG keys for this provider

### ISSUE THREAD

**Issue by yomovh** [terraform-provider-openstack/terraform-provider-openstack#1720] opened 2024-05-22 12:29 UTC
### OpenTofu Version

```bash
❯ tofu -version
OpenTofu v1.7.0
on darwin_arm64
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.14.0" 
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 2.0.0"
    }
  }
}
```

### Debug Output

```bash
❯ tofu init -upgrade
- Installing terraform-provider-openstack/openstack v2.0.0...
- Installed terraform-provider-openstack/openstack v2.0.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

**Comment by nikParasyr** [comment] 2024-05-23 12:49
have you used the provider with opentofu before?

cause i dont see the provider in the opentofu registry => https://github.com/opentofu/registry/tree/main/providers
havent had time to go through the process and understanding any possible issue

**Comment by yomovh** [comment] 2024-05-23 13:03
I have been using the 1.x for some time (though I do not check the signature at the `init`)

**Comment by nikParasyr** [comment] 2024-05-24 07:15
So i reached out to the opentofu people. Apparently the provider is part of the [registry](https://github.com/opentofu/registry/blob/main/providers/t/terraform-provider-openstack/openstack.json) so im just blind :P.

The above issue occurs because we haven't provided the public gpg key to them so that they can validate signatures etc.

The problem is that i do not have access to the public gpg key currently as it was created by a previous maintainer and i think im missing some required access level. I'll reach out to see whether i can get the right access otherwise we might want/need to create a new gpg key where i have to verify the impact of it and im still not sure i can do it due to missing access again.

**Comment by nikParasyr** [comment] 2024-05-25 09:54
Hopefully this will be resolved with => https://github.com/opentofu/registry/pull/614

**Comment by nikParasyr** [comment] 2024-05-26 07:04
This is fixed now with some help from the opentofu people:

```
❯ tofu init                                                               

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of terraform-provider-openstack/openstack from the dependency lock file
- Installing terraform-provider-openstack/openstack v2.0.0...
- Installed terraform-provider-openstack/openstack v2.0.0 (signed, key ID 4F80527A391BEFD2)

```

**Closed by nikParasyr** 2024-05-26 07:04 UTC
