### ISSUE TITLE
Two obvious bugs about openstack_containerinfra

### ISSUE THREAD

**Issue by GanFuWang** [terraform-provider-openstack/terraform-provider-openstack#1102] opened 2020-11-19 08:19 UTC
Hi there,
1. `floating_ip_enabled=true` is not take effect in openstack_containerinfra_clustertemplate_v1
2. I modify `node_count`, then apply ,it should be modify the node number of cluster, but it return error:  
```
Error: Error updating openstack_containerinfra_cluster_v1 c6350dd3-91c4-4106-a9ab-09d15635692d: Bad request with: [PATCH http://x.x.x.x:9511/v1/clusters/c6350dd3-91c4-4106-a9ab-09d15635692d], error message: {"errors": [{"request_id": "", "code": "client", "status": 400, "title": "Invalid input for field/attribute node_count", "detail": "Invalid input for field/attribute node_count. Value: '4'. '<' not supported between instances of 'str' and 'int'", "links": []}]}

  on os.tf line 41, in resource "openstack_containerinfra_cluster_v1" "cluster_1":
  41: resource "openstack_containerinfra_cluster_v1" "cluster_1" {

``` 

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/openstack v1.33.0

### Affected Resource(s)
openstack_containerinfra_cluster_v1
openstack_containerinfra_clustertemplate_v1

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name   = var.user_name
  tenant_name = var.tenant_name
  password    = var.password
  auth_url    = var.auth_url
  region      = var.region
}

resource "openstack_containerinfra_clustertemplate_v1" "clustertemplate_1" {
  name                  = var.clustertemplate_name
  image                 = var.image
  coe                   = "kubernetes"
  flavor                = var.flavor
  master_flavor         = var.master_flavor
  dns_nameserver        = "x.x.x.x"
  docker_storage_driver = "overlay2"
  docker_volume_size    = 40
  network_driver        = var.network_driver
  server_type           = "vm"
  master_lb_enabled     = var.master_lb_enabled
  floating_ip_enabled   = var.floating_ip_enabled
  external_network_id   = var.external_network_id
  fixed_network = var.fixed_network
  fixed_subnet = var.fixed_subnet

  labels = {
    kube_tag                         = var.kube_tag
    kube_dashboard_enabled           = "true"
    prometheus_monitoring            = "true"
    influx_grafana_dashboard_enabled = "true"
    container_infra_prefix           = "xxxxxx"
  }
}

resource "openstack_containerinfra_cluster_v1" "cluster_1" {
  name                = var.cluster_name
  cluster_template_id = openstack_containerinfra_clustertemplate_v1.clustertemplate_1.id
  master_count        = var.master_count
  node_count          = var.node_count
  keypair             = "mykey"
  floating_ip_enabled   = var.floating_ip_enabled
  timeouts {
    create = var.timeout
    delete = var.timeout
  }
}

variable "floating_ip_enabled"{
  type = bool
  default = true
}

variable "node_count" {
  type = number
  default = 4
}

```

**Comment by dhrp** [comment] 2021-03-23 11:11
I'm just reporting I run into the same issue , using latest:

**"Invalid input for field/attribute node_count. Value: '2'. '<' not supported between instances of 'str' and 'int'"**

```
terraform {
  required_version = ">= 0.14.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.39.0"
    }
  }
}
```

**Comment by www44** [comment] 2021-08-20 14:57
same for 
```
openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.43.0"
}
```

**Comment by pawcykca** [comment] 2021-12-30 15:22
Using below configuration I can create cluster with FIP assigned to all VMs:
`    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.43.0"
    }`

`resource "openstack_containerinfra_clustertemplate_v1" "clustertemplate_1" {
...
floating_ip_enabled   = true
...
}`

`resource "openstack_containerinfra_cluster_v1" "cluster_1" {
...
floating_ip_enabled = true
...
}`

**Comment by Mazorius** [comment] 2022-08-16 20:33
I had a look into the OpenStack API and the go code.

Can it be, that the problem is, that the code only send a patch event which does not support resizing?

[Line of code where the node_count is handled](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_containerinfra_cluster_v1.go#L416)

[Request that is used and not support node_count at least no more](https://docs.openstack.org/api-ref/clustering/?expanded=update-cluster-detail#update-cluster)

[The request that must be used in this case?](https://docs.openstack.org/api-ref/clustering/?expanded=update-cluster-detail#resize-a-cluster)

Maybe someone can be found that implement and test this.

**Comment by nikParasyr** [comment] 2022-08-19 11:32
> [Request that is used and not support node_count at least no more](https://docs.openstack.org/api-ref/clustering/?expanded=update-cluster-detail#update-cluster)
> [The request that must be used in this case?](https://docs.openstack.org/api-ref/clustering/?expanded=update-cluster-detail#resize-a-cluster)

this is a containerinfra resource that is using magnum => https://docs.openstack.org/api-ref/container-infrastructure-management/

The links you provide are from senlin, a different openstack service

**Comment by pawcykca** [comment] 2022-08-23 20:26
I have just pushed PR that should fix 2) problem.

**Comment by jan-di-cgm** [comment] 2022-09-22 13:37
@pawcykca Seems not to be fixed at all places. 
We are using provider v1.48, when changing the `min_node_count` of `openstack_containerinfra_nodegroup_v1` the same issue occurs:
 Invalid input for field/attribute min_node_count. Value: '1'. '<' not supported between instances of 'str' and 'int'

**Comment by pawcykca** [comment] 2022-09-22 18:58
@jan-di-cgm my PR (fixing this issue) wasn't merged and released yet ;-)

**Closed** 2022-10-02 08:30 UTC
